### ISSUE TITLE
添加假人支持以及生电模式等功能

### ISSUE THREAD

**Issue by bluefish-08** [LeavesMC/Lumina#1]
### 描述你希望添加的功能。 Describe the feature you'd like.

- [x] 支持假人
- [x] 配置文件中的生电模式

**Comment by MC-XiaoHei** [comment]
将部分task移动到 #7

**Comment by MC-XiaoHei** [comment]
生电模式方案已由 #18 决定默认开启，不再提供选项。

**Comment by MC-XiaoHei** [comment]
已经编写了需要修改默认值的配置项列表，即将实施

**Comment by MC-XiaoHei** [comment]
完成。
