### ISSUE TITLE
侦测器对着空气旁边的发射器没有激活

### ISSUE THREAD

**Issue by shulng** [LeavesMC/Lumina#24]

**Comment by GLDYM** [comment]
请提供更多的信息，比如这个侦测器与发射器具体是怎么摆的？我怀疑你少放了个音符盒

**Comment by shulng** [comment]
> 请提供更多的信息，比如这个侦测器与发射器具体是怎么摆的？

![QQ20240808-054038](https://github.com/user-attachments/assets/7a27d1d6-5115-47af-83e4-3317c041e4c5)

**Comment by MC-XiaoHei** [comment]
让我看看
