### ISSUE TITLE
在双维度机器中，如果对面没有地狱门非玩家实体也可以传送过去并创建地狱门

### ISSUE THREAD

**Issue by VinsonFather** [LeavesMC/Lumina#27]
### 预期的行为 Expected behavior

在1.20中，对面没有地狱门非玩家实体不会传送过去并创建地狱门

### 观测到的实际行为 Observed/Actual behavior

在1.20中，对面没有地狱门非玩家实体也可以传送过去并创建地狱门。

### 复现步骤 Steps/models to reproduce

https://www.bilibili.com/video/BV1Lm421x7VV

### 更多详细信息。 The more information.

https://www.bilibili.com/video/BV1Lm421x7VV

**Comment by MC-XiaoHei** [comment]
似乎1.21同样拥有此特性？你是否认为需要进行修复（Lumina大概不会在1.20.6发版）

**Comment by MC-XiaoHei** [comment]
如果不需要修复此特性，我将仅仅尝试修复#26中提到的问题

**Comment by MC-XiaoHei** [comment]
暂时close了
