### ISSUE TITLE
希望能添加假人重进

### ISSUE THREAD

**Issue by shulng** [LeavesMC/Lumina#29]
### 描述你希望添加的功能。 Describe the feature you'd like.

重启服务器假人会重新加入 或者死亡后重进

**Comment by MC-XiaoHei** [comment]
优先度会比较低

**Comment by shulng** [comment]
> 优先度会比较低

没事，慢慢来。

**Comment by MC-XiaoHei** [comment]
应该会等到 Leaves 重写完假人后我写一个单独的假人管理插件

**Comment by MC-XiaoHei** [comment]
> 应该会等到 Leaves 重写完假人后我写一个单独的假人管理插件

如上，这个功能不会被放到 Lumina 里面了
