### ISSUE TITLE
TAB闪烁

### ISSUE THREAD

**Issue by Kercute** [LeavesMC/Lumina#30]
当按下TAB打开时TAB列表会闪烁

**Comment by Kercute** [comment]
用的是最新构建https://github.com/LeavesMC/Lumina/actions/runs/10353060565，装上TAB4.1.6插件时就出现问题闪烁

**Comment by MC-XiaoHei** [comment]
大概是因为carpet移植那边log导致的，需要时间

**Comment by MC-XiaoHei** [comment]
等下 我好像理解错了，你是否安装了修改tab栏的插件？

**Comment by MC-XiaoHei** [comment]
经过测试，使用TAB插件时会有你所说的闪烁现象，已经在最新版本修复

**Comment by Kercute** [comment]
好耶
