### ISSUE TITLE
无法编译，

### ISSUE THREAD

**Issue by FateGodI** [LeavesMC/Lumina#38]
### 描述你希望添加的功能。 Describe the feature you'd like.

[root@centos-stream9 Lumina]# ./gradlew createMojmapBundlerJar

> Configure project :
paperweight-patcher v1.0.0-SNAPSHOT (running on 'Linux')

> Configure project :folia
paperweight-patcher v1.7.1 (running on 'Linux')

> Configure project :folia:paper
paperweight-core v1.7.1 (running on 'Linux')

> Task :lumina-server:compileJava FAILED
/root/Lumina/Lumina-Server/src/main/java/org/leavesmc/lumina/utils/DividedPlayerList.java:84: 错误: 进行语法分析时已到达文件结尾
        }
         ^
1 个错误

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':lumina-server:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --info option to get more log output.
> Run with --scan to get full insights.

BUILD FAILED in 7s
10 actionable tasks: 3 executed, 7 up-to-date

给我报了个源码文件DividedPlayerList.java的问题

**Comment by YuanYuanOwO** [comment]
~~这也不是新功能建议啊~~
去actions里下吧

**Comment by MC-XiaoHei** [comment]
https://github.com/LeavesMC/Lumina/issues/34
你们都看不到commit上写的[ci skip]吗？？
