### ISSUE TITLE
重力方块复制

### ISSUE THREAD

**Issue by s-yh-china** [LeavesMC/Lumina#5]
### 预期的行为 Expected behavior

利用末地门可以复制重力方块

### 观测到的实际行为 Observed/Actual behavior

利用末地门不能复制重力方块

### 复现步骤 Steps/models to reproduce

建造刷沙机 不能使用

**Comment by MC-XiaoHei** [comment]
需要开启对应配置 https://docs.papermc.io/paper/reference/global-configuration#unsupported_settings

**Comment by s-yh-china** [comment]
可 那就关
