### ISSUE TITLE
图标讨论

### ISSUE THREAD

**Issue by MC-XiaoHei** [LeavesMC/Lumina#9]
我找了个图标，或许可以作为Lumina图标（？
同时拥有 `光` 和 `叶` 的元素
@s-yh-china @LittleChest @Bluemangoo

**Comment by s-yh-china** [comment]
我们可以直接使用吗? 还是把这个作为模板绘制新的

**Comment by MC-XiaoHei** [comment]
怎么网页渲染不出来svg啊。。
贴个png吧
![lumina](https://github.com/LeavesMC/Lumina/assets/100807593/4d912624-4a2f-4b10-bfdb-6b31d59a61b2)

**Comment by MC-XiaoHei** [comment]
> 我们可以直接使用吗? 还是把这个作为模板绘制新的

可以直接使用

**Comment by Bluemangoo** [comment]
你的svg有问题，自己手改下。

**Comment by MC-XiaoHei** [comment]
生成这个图标网站上面标的是50刀带版权。。
改改用？

**Comment by Bluemangoo** [comment]
你不会让狗屁通画一个然后ps改改转svg吗。反正wrs的图标是这样子来的。

**Comment by MC-XiaoHei** [comment]
> 你不会让狗屁通画一个然后ps改改转svg吗。反正wrs的图标是这样子来的。

但是这个图标真的好看（
我看看能不能改改元素，防止版权问题。

**Comment by LittleChest** [comment]
> 我找了个图标，或许可以作为Lumina图标（？
> ![lumina](https://github.com/LeavesMC/Lumina/assets/100807593/15ff31c1-7c6d-49a4-b3d3-18dcc9d9c006)
> 同时拥有 `光` 和 `叶` 的元素
> @s-yh-china @LittleChest @Bluemangoo 

缩略图呢 这也太复杂了（

**Comment by Bluemangoo** [comment]
![image](https://github.com/LeavesMC/Lumina/assets/63218454/91b48b96-35eb-4274-a428-7d3bf11cf4f6)
![image](https://github.com/LeavesMC/Lumina/assets/63218454/b5263364-fb8a-426c-aa90-d819014e58b8)

[狗屁通](https://www.bing.com/images/create/a-simple-green-icon-with-a-light-element-and-a-lea/2-661721024b4a4af7bd9022c4a10c81bb?id=p5eQYLT5C%2BKnyAUZH2DunA%3D%3D&view=detailv2&idpp=genimg&idpclose=1&thid=OIGBCE1.HgJp4DVk7ZaNV3fIcFNq&form=SYDBIC)画的。

**Comment by MC-XiaoHei** [comment]
我觉得可以，可以改改用
